name: build

on:
  push:
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar SDL2 para 3DS
        run: dkp-pacman -S --noconfirm --needed 3ds-sdl2

      - name: Compilar
        working-directory: hello-world
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE="$DEVKITPRO/cmake/3DS.cmake"
          cmake --build build

      - uses: actions/upload-artifact@v4
        with:
          name: hello_n3ds
          path: hello-world/build/*.3dsx
